import json
import numpy as np
import torch
from transformers import pipeline


class InferlessPythonModel:

    # replace ##task_type## and ##huggingface_name## with appropriate values
    def initialize(self):
        self.generator = None

    # inputs is a dictonary where the keys are input names and values are actual input data
    # e.g. in the below code the input name is prompt 
    # The output generated by the infer function should be a dictonary where keys are output names and values are actual output data
    # e.g. in the below code the output name is generated_txt
    def infer(self, inputs):
        print("type of inputs dict" +  type(inputs))
        for idx, x in enumerate(inputs):
            print(idx, x)
        return {"generated_text": "test"}

    # perform any cleanup activity here
    def finalize(self,args):
        self.pipe = None
        
